:hivemq-link: https://www.hivemq.com
:hivemq-extension-docs: {hivemq-link}/docs/extensions/latest/
:hivemq-mqtt-toolbox: {hivemq-link}/mqtt-toolbox
:hivemq-support: {hivemq-link}/support/
:hivemq-testcontainer: https://github.com/hivemq/hivemq-testcontainer
:hivemq-mqtt-client: https://github.com/hivemq/hivemq-mqtt-client

= HiveMQ 4 Hello Retain Extension

image:https://img.shields.io/badge/Extension_Type-Demonstration-orange?style=for-the-badge[Extension Type]
image:https://img.shields.io/github/v/release/hivemq/hivemq-hello-world-extension?style=for-the-badge[GitHub release (latest by date),link=https://github.com/hivemq/hivemq-hello-world-extension/releases/latest]
image:https://img.shields.io/github/license/hivemq/hivemq-hello-world-extension?style=for-the-badge&color=brightgreen[GitHub,link=LICENSE]
image:https://img.shields.io/github/actions/workflow/status/hivemq/hivemq-hello-world-extension/check.yml?branch=master&style=for-the-badge[GitHub Workflow Status,link=https://github.com/hivemq/hivemq-hello-world-extension/actions/workflows/check.yml?query=branch%3Amaster]

== Purpose

This Hello Retain extension registers a PublishInboundInterceptor to modify the Retain flag of every Publish with the client ID 'client1' to `true`.

We strongly recommend to read the {hivemq-extension-docs}[HiveMQ Extension Documentation] to grasp the core concepts of HiveMQ extension development.

== Installation

. Clone this repository into a Java 21 Gradle project.
. Execute the Gradle task `hivemqExtensionZip` to build the extension.
. Move the file: `build/hivemq-extension/retain-extension-4.36.0.zip` to the directory: `HIVEMQ_HOME/extensions`
. Unzip the file.
. Start HiveMQ.

== First Steps

=== Manual Testing

Connect with https://hivemq.github.io/mqtt-cli/[MQTT-CLI] client ID 'client1'.
Publish a message with `retain flag `false` from client ID 'client1' to topic 'test'.

```sh
mqtt publish --identifier client1 --topic test --message 'I am originally not retained' --qos 1
```

Subscribe a client to the same topic 'test'.

```sh
mqtt subscribe --identifier subscriber --topic test --qos 1 --json-output
```

The subscriber should receive the message with `retain` flag `true` from the broker.
```
{
  "topic": "test",
  "payload": "I am originally not retained",
  "qos": "AT_LEAST_ONCE",
  "receivedAt": "2025-02-19 14:47:43",
  "retain": true
}
```

=== Automatic Testing

Execute the `HelloWorldInterceptorIT` for automatic testing of the extension.
It uses the {hivemq-testcontainer}[HiveMQ Testcontainer] to automatically package, deploy and run the extension inside a HiveMQ docker container.
The test creates a {hivemq-mqtt-client}[HiveMQ MQTT Client] to publish and receive a message with the clientID 'client1'.
It checks whether the Retain flag has been changed correctly to `true`.

== Next Steps

Awesome, you got the extension working.

Now read the {hivemq-extension-docs}[HiveMQ Extension Documentation] to see what extensions can do.

== Need Help?

If you encounter any problems, we are happy to help.
The best place to get in contact is our {hivemq-support}[support^].

== Contributing

If you want to contribute to HiveMQ Hello Retain Extension, see the link:CONTRIBUTING.md[contribution guidelines].

== License

HiveMQ Hello Retain Extension is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].
